kind: Service
apiVersion: v1
metadata:
  name: readiness-chk-app-service
spec:
  selector:
    app: readiness-chk-app
  ports:
    - name: incorrect-port 
      protocol: TCP
      port: 6665
      targetPort: 6665
    - name: correct-port
      protocol: TCP
      port: 6666
      targetPort: 6666
